name = "word30210/super_table"
version = "0.1.0"
authors = ["word30210"]
repository = "https://github.com/Word30210/super-table"
license = "MIT"
includes = [
  "pesde.toml",
  "README.md",
  "LICENSE",
  "src/**",
  ".luaurc",
  "scripts"
]

[target]
environment = "luau"
lib = "src/init.luau"

[target.scripts]
build = "scripts/build.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.0"
lune = "^0.10.2"

[dev_dependencies]
frktest = { name = "itsfrank/frktest", version = "^0.0.2", target = "lune" }
multitarget = { name = "ewdev/multitarget", version = "^0.4.2-rc.7", target = "lune" }